server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://db:5432/minidoodle
    username: minidoodle_user
    password: minidoodle_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
